### ISSUE TITLE
Create default matrix exclusions

### ISSUE THREAD

**Issue by rossabaker** [http4s/sbt-http4s-org#110]
http4s builds all the Scalas on the base Java, and all the Javas on one preferred Scala.  This might be sensible throughout the org.

**Comment by armanbilge** [comment]
We've since adopted this pattern in the CE build too. I wonder if it can be pushed up an sbt-spiewak default.

**Comment by rossabaker** [comment]
That sounds good to me, but we don't know the default Scala or Java there the way that we do within the org.  Could pick a head or tail, but that assumes everyone sorts them the same way.
