### ISSUE TITLE
Refreshing the Sonatype credentials is required

### ISSUE THREAD

**Issue by danicheg** [http4s/sbt-http4s-org#268]
We've run into this issue when publishing `v0.17.2`
```
2024-07-20 10:09:47.422Z  info [SonatypeClient] Uploading bundle /home/runner/work/sbt-http4s-org/sbt-http4s-org/target/sonatype-staging/0.17.2 to https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/orghttp4s-1258/  - (SonatypeClient.scala:274)
2024-07-20 10:09:47.737Z error [Sonatype] 
java.io.IOException: Failure:java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
```
https://github.com/http4s/sbt-http4s-org/actions/runs/10019401723/job/27695950559#step:14:82
It's an organization-wide issue 🔥

**Comment by danicheg** [comment]
@rossabaker i'm mentioning you for better visibility (no rush though).

**Comment by rossabaker** [comment]
Sorry, I was on vacation and not reading notifications.  I fixed this sometime last week.  I reran the v0.17.2 build today and it appears to have worked.

I'm going to get those credentials shared somewhere so I'm not a single point of failure.

**Comment by rossabaker** [comment]
I added it credentials to a shared Typelevel space, for lack of a shared http4s space.  The Steering Committee can help if this happens again and I'm unavailable.
