### ISSUE TITLE
Replace JDK16 with JDK17

### ISSUE THREAD

**Issue by rossabaker** [http4s/sbt-http4s-org#94]
I don't know what's available out of the box yet.  It took a few weeks before we could upgrade to 16, but 17 is more exciting.

**Comment by rossabaker** [comment]
https://github.com/http4s/sbt-http4s-org/issues/94

**Comment by armanbilge** [comment]
We may need a custom jabba index as discussed in https://github.com/typelevel/cats-effect/pull/2218.

**Comment by rossabaker** [comment]
If multiple Typelevel projects are going to need one of these, the Typelevel repo with a bus factor > 1 seems wise?

**Comment by armanbilge** [comment]
That was my vote too.

**Comment by vasilmkd** [comment]
This is my index https://github.com/vasilmkd/jdk-index. I would be more than happy to make it an official project.

**Comment by vasilmkd** [comment]
I have to issue a small warning, setting up the project would require a bit of bikeshedding.

I intentionally broke compatibility with the official jabba index versioning (I use `8, 11, 17` instead of `1.8, 1.11, 1.17`) and I also changed `adopt` to `adoptium` to differentiate the switch from https://adoptopenjdk.net to https://adoptium.net

**Comment by rossabaker** [comment]
I'm old enough to be confused that I can't still just download it from Sun.  I'm happy to follow whatever is working on cats-effect.

**Comment by rossabaker** [comment]
I forked @vasilmkd's into typelevel and made him an admin.

**Comment by vasilmkd** [comment]
As I'm already a Typelevel member, is there a possibility to actually donate the original repo?

**Comment by rossabaker** [comment]
Yeah, we could delete the fork and you could transfer it in.  I was just worried about breaking existing references with that approach.  You could always fork it back.

**Comment by vasilmkd** [comment]
I will fork it back immediately, yes.

**Comment by rossabaker** [comment]
Alright, I'll leave it to you, and let me know if you hit any permissions snags.

**Comment by vasilmkd** [comment]
@rossabaker The transfer is complete. Can you please set me as collaborator or admin again?

**Comment by rossabaker** [comment]
Done.

**Comment by vasilmkd** [comment]
@rossabaker From which branch should I start the migration of the build?

**Comment by vasilmkd** [comment]
Nevermind, found it, it's in this repo only. Perfect.

**Comment by rossabaker** [comment]
Can we do it in this repo and have it be transitive?

**Comment by vasilmkd** [comment]
And right on cue, the Adoptium final JDK 17 images dropped!

**Comment by rossabaker** [comment]
Fixed by #95

**Comment by LeifW** [comment]
> I'm old enough to be confused that I can't still just download it from Sun. I'm happy to follow whatever is working on cats-effect.

Oracle did change the licensing for JDK 17 so you can just download via curl w/out requiring some click-through to accept their license agreement: https://jdk.java.net/17/ (and also you can use their commercial JDK in prod w/out paying them). So personally I'm switching from the adoptopenjdk / eclipse-temurin / whatever docker images to the oracle-provided openjdk one for 17.

**Comment by rossabaker** [comment]
I'm open to that.  I currently run my work machine on a custom nix derivation of some bonkers GraalVM CE version that was in the onboarding guide.  20 years on the JVM, and I don't know what's cool anymore.

**Comment by vasilmkd** [comment]
@rossabaker I can add the Oracle JDK to the typelevel index and it becomes available to the CI, it just needs to be selected. However, we can only do that for JDK 17, the new licensing does not apply to the previous releases.

**Comment by rossabaker** [comment]
I'm good with the adoptium one unless there's a reason to switch back.
